name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install uv with Python 3.14
      uses: astral-sh/setup-uv@v7
      with:
          python-version: 3.14
    - name: Get submodules
      run: |
        git submodule update --init --recursive
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        uv build --sdist
        uvx twine upload dist/*
